name: vice-jz
version: 3.2
summary: Versatile Commodore Emulator
description: |
  VICE executes programs intended for the old 8-bit computers. The current 
  version emulates the C64, the C64DTV, the C128, the VIC20, practically all PET
  models, the PLUS4 and the CBM-II (aka C610/C510). An extra emulator is
  provided for C64 expanded with the CMD SuperCPU. 

grade: stable
confinement: strict

apps:
  c1541:
    command: desktop-launch override-x11 c1541
    plugs: [home]

  cartconv:
    command: cartconv
    plugs: [home]

  petcat:
    command: petcat
    plugs: [home]

  vsid:
    command: vsid
    plugs: [home]

  x128:
    command: desktop-launch override-x11 x128
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  x64:
    command: desktop-launch override-x11 x64
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  x64dtv:
    command: desktop-launch override-x11 x64dtv
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  x64sc:
    command: desktop-launch override-x11 x64sc
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  xcbm2:
    command: desktop-launch override-x11 xcbm2
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  xcbm5x0:
    command: desktop-launch override-x11 xcbm5x0
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  xpet:
    command: desktop-launch override-x11 xpet
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  xplus4:
    command: desktop-launch override-x11 xplus4
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  xscpu64:
    command: desktop-launch override-x11 xscpu64
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

  xvic:
    command: desktop-launch override-x11 xvic
    plugs: [home, x11, wayland, desktop, desktop-legacy, pulseaudio, joystick, io-ports-control]

plugs:
  gnome-3-26-1604:
    default-provider: gnome-3-26-1604:gnome-3-26-1604
    interface: content
    target: $SNAP/gnome-platform

parts:
  vice:
    source: https://downloads.sourceforge.net/project/vice-emu/releases/vice-3.2.tar.gz
    plugin: autotools
    build-attributes:
      - no-system-libraries
    configflags:
      - --prefix=/snap/vice-jz/current
      - --enable-gnomeui3
      - --enable-fullscreen
      - --disable-parsid
      - --with-midas
      - --without-xaw3d
      - --enable-arch=no
      - --enable-vte
      - --with-jpeg
      - --enable-lame
      - --with-pulse
    build-packages:
      - bison
      - flex
      - texinfo
      - libreadline-dev
      - libjpeg-dev
      - libpng-dev
      - libgtk-3-dev
      - libasound2-dev
      - libpulse-dev
      - libmp3lame-dev
      - libavformat-dev
      - libieee1284-3-dev
      - libgtkglext1-dev
      - libvte-2.91-dev
      - libswscale-dev
      - xfonts-utils
      - yasm
    prime:
      - -var
      - -share/info
      - -share/man
      - -usr/share/alsa
      - -usr/share/apport
      - -usr/share/avahi
      - -usr/share/bug
      - -usr/share/dbus-1
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/mime
      - -usr/share/pkgconfig
      - -snap
    organize:
      snap/vice-jz/current/bin: bin
      snap/vice-jz/current/lib64: lib64
      snap/vice-jz/current/share: share
    after:
      - desktop-gnome-platform
    override-build: |
      PNAME=linux_no_emultest.patch
      echo Applying $PNAME
      cat $SNAPCRAFT_STAGE/../$PNAME | patch -p1
      echo Patching done
      snapcraftctl build
      echo Stripping executables
      strip $SNAPCRAFT_PART_INSTALL/snap/vice-jz/current/bin/*

  # https://bazaar.launchpad.net/~ubuntu-desktop/+junk/ghex-snap-gnome-3-24/view/head:/snapcraft.yaml

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    prime:
      - "-*"

  launcher:
    plugin: dump
    source: launcher
    organize:
      override-x11: bin/
