name: vice-jz
version: 3.1-0
summary: Versatile Commodore Emulator
description: |
  VICE executes programs intended for the old 8-bit computers. The current 
  version emulates the C64, the C64DTV, the C128, the VIC20, practically all PET
  models, the PLUS4 and the CBM-II (aka C610/C510). An extra emulator is
  provided for C64 expanded with the CMD SuperCPU. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  c1541:
    command: desktop-launch c1541
    plugs: [home]

  cartconv:
    command: cartconv
    plugs: [home]

  petcat:
    command: petcat
    plugs: [home]

  vsid:
    command: vsid
    plugs: [home]

  x128:
    command: desktop-launch x128
    plugs: [home, unity7, pulseaudio]

  x64:
    command: desktop-launch x64
    plugs: [home, unity7, pulseaudio]

  x64dtv:
    command: desktop-launch x64dtv
    plugs: [home, unity7, pulseaudio]

  x64sc:
    command: desktop-launch x64sc
    plugs: [home, unity7, pulseaudio]

  xcbm2:
    command: desktop-launch xcbm2
    plugs: [home, unity7, pulseaudio]

  xcbm5x0:
    command: desktop-launch xcbm5x0
    plugs: [home, unity7, pulseaudio]

  xpet:
    command: desktop-launch xpet
    plugs: [home, unity7, pulseaudio]

  xplus4:
    command: desktop-launch xplus4
    plugs: [home, unity7, pulseaudio]

  xscpu64:
    command: desktop-launch xscpu64
    plugs: [home, unity7, pulseaudio]

  xvic:
    command: desktop-launch xvic
    plugs: [home, unity7, pulseaudio]

plugs:
    gnome-3-24-platform:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-24:gnome-3-24-platform

parts:
  vice:
    source: https://downloads.sourceforge.net/project/vice-emu/releases/vice-3.1.tar.gz
    plugin: autotools
    configflags:
      - --prefix=
      - --enable-gnomeui3
      - --enable-fullscreen
      - --disable-parsid
      - --with-midas
      - --without-xaw3d
      - --enable-arch=no
      - --enable-vte
      - --with-jpeg
      - --enable-lame
      - --with-pulse
    build-packages:
      - bison
      - flex
      - texinfo
      - libreadline-dev
      - libjpeg-dev
      - libpng-dev
      - libgtk-3-dev
      - libasound2-dev
      - libpulse-dev
      - libmp3lame-dev
      - libavformat-dev
      - libieee1284-3-dev
      - libgtkglext1-dev
      - libvte-2.91-dev
      - libswscale-dev
      - xfonts-utils
      - yasm
    stage-packages:
      - libasound2
      - libpulse0
      - libreadline6
      - libvte-2.91-0
      - zlib1g
    prime:
      - -var
      - -share/info
      - -share/man
      - -usr/share/apport
      - -usr/share/avahi
      - -usr/share/man

  desktop-gnome-platform:
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    source: https://github.com/kenvandine/snapcraft-desktop-helpers.git
    source-branch: gnome-3-24
    install: mkdir -p $SNAPCRAFT_PART_INSTALL/gnome-platform

  # https://bazaar.launchpad.net/~ubuntu-desktop/+junk/ghex-snap-gnome-3-24/view/head:/snapcraft.yaml

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    stage-packages:
      - libgtk-3-0
    prime:
      - "-*"

